"""update

Revision ID: 1124bf2d7ae8
Revises: 
Create Date: 2026-09-27 21:57:28.693895

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1124bf2d7ae8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Projects_Table', schema=None) as batch_op:
        batch_op.drop_column('markdown')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Projects_Table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('markdown', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
