"""update

Revision ID: 26dc3e008cd8
Revises: 
Create Date: 2026-09-29 18:23:55.687551

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26dc3e008cd8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Projects_Table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('likes', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Projects_Table', schema=None) as batch_op:
        batch_op.drop_column('likes')

    # ### end Alembic commands ###
