"""update

Revision ID: 373ee38820f4
Revises: ab96640daee8
Create Date: 2026-09-30 02:39:30.935481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '373ee38820f4'
down_revision = 'ab96640daee8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Projects_Table', schema=None) as batch_op:
        batch_op.alter_column('completed',
               existing_type=sa.DATE(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Projects_Table', schema=None) as batch_op:
        batch_op.alter_column('completed',
               existing_type=sa.DATE(),
               nullable=True)

    # ### end Alembic commands ###
