"""update

Revision ID: 77717f489b69
Revises: f9bdbc89886f
Create Date: 2026-09-30 21:11:37.099966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77717f489b69'
down_revision = 'f9bdbc89886f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Skills_Table', schema=None) as batch_op:
        batch_op.alter_column('skill',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=15),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Skills_Table', schema=None) as batch_op:
        batch_op.alter_column('skill',
               existing_type=sa.String(length=15),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###
