"""update to description

Revision ID: 77c90250d0fe
Revises: a21a90382812
Create Date: 2026-09-28 23:18:12.038577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77c90250d0fe'
down_revision = 'a21a90382812'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Skills_Table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Skills_Table', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
