"""update

Revision ID: a21a90382812
Revises: 1124bf2d7ae8
Create Date: 2026-09-28 21:15:27.594661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a21a90382812'
down_revision = '1124bf2d7ae8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Projects_Table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completed', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Projects_Table', schema=None) as batch_op:
        batch_op.drop_column('completed')

    # ### end Alembic commands ###
