"""update

Revision ID: ab96640daee8
Revises: 26dc3e008cd8
Create Date: 2026-09-29 20:17:09.300828

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab96640daee8'
down_revision = '26dc3e008cd8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Projects_Table', schema=None) as batch_op:
        batch_op.alter_column('likes',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Projects_Table', schema=None) as batch_op:
        batch_op.alter_column('likes',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
